# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
services:
    Aws\S3\S3Client:
        arguments:
            - version: '2006-03-01'
              region: 'us-east-1'
              credentials:
                  key: '%env(S3_STORAGE_KEY)%'
                  secret: '%env(S3_STORAGE_SECRET)%'
flysystem:
    storages:
        headshots.storage:
            adapter: 'aws'
            options:
                client: 'Aws\S3\S3Client'
                bucket: '%env(S3_HEADSHOTS_BUCKET)%'
                prefix: '%env(S3_HEADSHOTS_PREFIX)%'
