# Read the documentation: https://github.com/1up-lab/OneupUploaderBundle/blob/master/Resources/doc/index.md
oneup_uploader:
    mappings:
        headshots:
            frontend: dropzone
            storage:
                type: flysystem
                filesystem: oneup_flysystem.headshots_filesystem
