# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle
oneup_flysystem:
    adapters:
        headshots_adapter:
            awss3v3:
                client: acme.s3_client
                bucket: '%env(S3_HEADSHOTS_BUCKET)%'
                prefix: '%env(S3_HEADSHOTS_PREFIX)%'
                options:
                    ACL: public-read
        documents_adapter:
            awss3v3:
                client: acme.s3_client
                bucket: '%env(S3_DOCUMENTS_BUCKET)%'
                prefix: '%env(S3_DOCUMENTS_PREFIX)%'
                options:
                    ACL: public-read
    filesystems:
        headshots:
            adapter: headshots_adapter
            alias: League\Flysystem\Filesystem $headshotsFilesystem
        documents:
            adapter: documents_adapter
            alias: League\Flysystem\Filesystem $documentsFilesystem
